### ISSUE TITLE
Possible Error in Anatomy of a STARK, Part 1: STARK Overview

### ISSUE THREAD

**Issue by nattrad** [aszepieniec/stark-anatomy#11]
Hello! Been studying STARKs, found this is in Part 1 of the Anatomy of a STARK, in the Cryptographic Compilation with FRI section.

![image](https://user-images.githubusercontent.com/107082480/174202115-2f033c3e-4c74-4343-a974-866f6aff1e8a.png)

Is the non-interactive proof system described here suppose to be a SNARK and not a STARK?

**Comment by aszepieniec** [comment]
That depends on whether the meaning of the term "STARK" includes what is being described.

 - STARK$_1$: a scalable transparent proof system for arguments of knowledge
 - STARK$_2$: a concrete way of building SNARKs using AIRs and AETs etc
 - STARK$_3$, the SNARK proof that results from this construction

The end-result after applying the Fiat-Shamir transform is certainly a SNARK. But what is being described in this text is STARK$_2$. In this context, the end-result is also is a STARK$_3$.
