### ISSUE TITLE
Random vs independent index folding chart is wrong

### ISSUE THREAD

**Issue by juan-fence** [aszepieniec/stark-anatomy#16]
When reading index folding section of the chapter 3: FRI (https://aszepieniec.github.io/stark-anatomy/fri#index-folding) I am having a hard time making sense of the chart, the index folding half. 

I'd say the bottom two levels should be blue (as the points have been chosen from the blue parts in the malicious hybrid codeword)

Does this make sense? 

Thanks for putting this together!

**Comment by aszepieniec** [comment]
In both cases, the attacker tries to shift from a far-from-low-degree codeword (blue) to a close-to-low-degree codeword (green). The codewords are set by the attacker; the indices are only known after after the codewords are committed to.

The picture on the right shows why the attack fails: there has to be a colinearity check of mismatched colors.

**Comment by juan0xmon** [comment]
Yes, that is what I understood but I still don't follow the chart. 
![image](https://user-images.githubusercontent.com/108086552/186146421-ca81b01c-466c-4953-8ebd-393b1f457eed.png)

The way I see it, as the second round of indices is sampling from the bad (blue) part of the hybrid codeword, it should lead to the bottom layer being the bad codeword (blue). 

Unless I am not following the chart logic (but I agree with your previous comment), the bottom two layers should be blue too (and are green). I thought the chart tries to convey the following message: "if you start bad (blue) you will end up bad (blue) with the right indices but you may end up green with the random indices". Is this it?

Or I am misunderstanding how you represent your previous comment in a chart?

**Comment by aszepieniec** [comment]
You misunderstand my comment. The red arrows do not indicate what is being copied, they indicated what is being checked. The codewords are fixed before the locations of the red arrows are sampled.

**Comment by juan0xmon** [comment]
Ahhh got it. 

So in the second step you would be comparing A, and B from blue to C from green (as the prover has now shifted to full green), which wouldn't be in the same line. 

Thank you again!
