### ISSUE TITLE
[Question] Minor questions about this tutorial

### ISSUE THREAD

**Issue by jonathanxuu** [aszepieniec/stark-anatomy#3]
Thank you very much for writing this series of tutorials. It's a great study material for me. In the process of learning I had some small questions:

In Part 1: STARK Overview, here's what got me wondering:
> `Interpolation and Polynomial IOPs`: …… At this point the AIR constraints give rise to _**operations polynomials**_ that _**send low-degree polynomials to low-degree polynomials**_ only if the constraints are satisfied. The verifier simulates these operations and can thus derive new polynomials whose low degree certifies the satisfiability of the constraint system, and thus the integrity of the computation.

1. what do 'operations polynomials' stand for ? Or maybe I got something wrong with my sentence break...?
2. 'send low-degree polynomials to low-degree polynomials' means what ? After having the AIR constraints, I think it's the time for getting 'quotients' , what do the two 'low-degree polynomials' here refer to respectively?

I would appreciate it if you could answer my questions above.

**Comment by aszepieniec** [comment]
1. Excuse me, that should be: *operations **on** polynomials*.
2. The preimage of this map is a trace polynomial; the afterimage of this map is a quotient. The quotient is a low degree polynomial if and only if the trace polynomial is a low degree polynomial and satisfies the AIR constraint.
