### ISSUE TITLE
omicron variables are not assigned at all?

### ISSUE THREAD

**Issue by KillariDev** [aszepieniec/stark-anatomy#6]
Hey I am confused about these lines in stark.py in prove() function
```
# symbolically evaluate transition constraints
point = [Polynomial([self.field.zero(), self.field.one()])] + trace_polynomials + [tp.scale(self.omicron) for tp in trace_polynomials]
transition_polynomials = [a.evaluate_symbolic(point) for a in transition_constraints]
```
Isn't the point bigger array than transition_constraints have variables? And thus these omicron variables are not being assigned at all?

**Comment by aszepieniec** [comment]
The multivariate polynomials in `transition_constraints` should have 2w+1 variables, and that should also be the number of elements in `point`.

**Comment by KillariDev** [comment]
ah, you are right! Thank you.
